// Generated by CoffeeScript 1.4.0
(function() {
  var Context, eio, http, k, socket, v, _ref;

  http = require('http');

  Context = require('./context');

  socket = require('./sockets');

  eio = require('engine.io');

  exports.version = '0.0.0';

  exports.Context = Context;

  exports.Socket = socket.Socket;

  _ref = socket.types;
  for (k in _ref) {
    v = _ref[k];
    exports[k.toUpperCase()] = v;
  }

  exports.listen = function(port, host, options, callback) {
    var context;
    if ('number' !== typeof port && !(port instanceof http.Server)) {
      throw new Error("First argument of SocketMQ#listen must be instance of http.Server or port number");
    }
    context = new Context;
    return context.listen(port, host, options, callback);
  };

  exports.connect = function(url) {
    var context;
    context = new Context;
    return context.connect(url);
  };

  exports.proxy = function() {};

}).call(this);
