// Generated by CoffeeScript 1.4.0
(function() {
  var k, socket, sockets, v;

  socket = require('./socket');

  for (k in socket) {
    v = socket[k];
    exports[k] = v;
  }

  sockets = {
    req: require('./req'),
    rep: require('./rep'),
    pub: require('./pub'),
    sub: require('./sub'),
    push: require('./push'),
    pull: require('./pull')
  };

  exports.sockets = sockets;

}).call(this);
