// Generated by CoffeeScript 1.4.0
(function() {
  var PubSocket, Socket, debug, types, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./socket'), Socket = _ref.Socket, types = _ref.types;

  debug = require('debug')('socketmq:pub');

  PubSocket = (function(_super) {

    __extends(PubSocket, _super);

    function PubSocket(context, options) {
      PubSocket.__super__.constructor.call(this, context, 'pub', options);
    }

    PubSocket.prototype.send = function(data) {
      var conn, _i, _len, _ref1, _results;
      _ref1 = this.connections;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        conn = _ref1[_i];
        _results.push(this.context.send(this, conn, data));
      }
      return _results;
    };

    return PubSocket;

  })(Socket);

  module.exports = PubSocket;

}).call(this);
