// Generated by CoffeeScript 1.4.0
(function() {
  var ReqSocket, Socket, types, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ref = require('./socket'), Socket = _ref.Socket, types = _ref.types;

  ReqSocket = (function(_super) {

    __extends(ReqSocket, _super);

    function ReqSocket(context, options) {
      ReqSocket.__super__.constructor.call(this, context, 'req', options);
      this.flushing = false;
    }

    ReqSocket.prototype.send = function(data) {
      return this.flushRoundRobin(data);
    };

    ReqSocket.prototype.handleMessage = function(conn, data) {
      this.connections.push(conn);
      this.emit('message', data);
      return this.flushRoundRobin();
    };

    ReqSocket.prototype.handleConnect = function(conn) {
      ReqSocket.__super__.handleConnect.call(this, conn);
      return this.flushRoundRobin();
    };

    return ReqSocket;

  })(Socket);

  module.exports = ReqSocket;

}).call(this);
